### ISSUE TITLE
Displaced Hint with Bootstrap 4

### ISSUE THREAD

**Issue by anyhowes** [fitiskin/jquery-autocompleter#25]
Hi there,

Thanks for building this nifty autocompleter! I'm really enjoying using it with a little project I'm working on. The only hiccup I've run into so far is that the hint div and span end up getting displayed outside of the input box (specifically, below the input box). This ends up overlapping with the first row of the drop down list (see screenshot). I'm wondering if there is something with Bootstrap 4 (which I'm using) that is interfering with the placement of the hint? If you have any ideas for a fix, they would be greatly appreciated!

Thanks.
![screen shot 2017-06-28 at 1 01 45 pm](https://user-images.githubusercontent.com/12585917/27657596-11fe8668-5c02-11e7-8d5b-7c9e61a370ed.png)

**Comment by fitiskin** [comment]
Forgive me for abandoning the project and answering you a few years later.

Bootstrap 4 example with a hint: https://codesandbox.io/s/jquery-autocompleter-bootstrap-4-died3v?file=/src/styles.css

It doesn't work well actually. The core idea here is to use CSS `top` property:

**CSS**
```css
.custom .autocompleter-hint {
  top: -37px; /* <-- HERE */

  color: #6c757d;
  text-align: left;
  line-height: 1.5;
  left: 0;
  width: 100%;
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
}
```
